## YAML Template.
---
endpoints :
    shutdown :
        enabled : true
        
spring:
    mvc:
        favicon:
            enabled: false
    oauth2:
        client:
            client-id: kanban
            client-secret: nosecret
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/Sites/dev/co2/kyt
        username: sa
        password: sa
    jpa: 
        hibernate:
            ddl-auto: update 
logging:
    level:
        org.springframework.security: INFO
        org.hibernate: INFO
---

endpoints :
    shutdown :
        enabled : false
            
spring:
    profiles: heroku
    datasource:
        platform: postgresql
        driverClassName: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        username: sa
        password: sa
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true