## YAML Template.
---
endpoints :
    shutdown :
        enabled : true
        
spring:
    oauth2:
        client:
            client-id: kanban
            client-secret: nosecret
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/Sites/dev/co2/kyt
        username: sa
        password: sa
    jpa: 
        hibernate:
            ddl-auto: update 
logging:
    level:
        org.springframework.security: INFO
        org.hibernate: INFO