## YAML Template.
---
endpoints :
    shutdown :
        enabled : true

spring:
    profiles:
        active: dev-postgresql 
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
    mvc:
        favicon:
            enabled: false
    oauth2:
        client:
            client-id: kanban
            client-secret: nosecret
liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
logging:
    level:
        org.springframework.security: INFO
        org.hibernate: INFO

---
           
spring:
    profiles: dev-h2
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/Sites/dev/co2/kyt
        username: sa
        password: sa

---
            
spring:
    profiles: dev-postgresql
    datasource:
        platform: postgresql
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql:postgres
        username: postgres
        password: Wxegdej5
liquibase:
    drop-first: false
---

endpoints :
    shutdown :
        enabled : false
            
spring:
    profiles: heroku
    datasource:
        platform: postgresql
        driverClassName: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true